### ISSUE TITLE
Sankey keyboard nav

### ISSUE THREAD

**Issue by mmazanec22** [nteract/semiotic#279]
Keyboard nav for network data is going to be a doozy.  Here's one idea:
- top left node start (in general keyboard nav should follow order of visual display)
- up and down keys from node to node at that level (this might be hard to determine in the middle of the diagram?)
- right arrow key from node to get to that node's top link, then up and down keys to navigate among that node's links
- right arrow to get to next node from that link

**Comment by emeeks** [comment]
:O
