### ISSUE TITLE
Animated Sparklines

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#288]
I haven't played around with sparklines in Semiotic much but I came across this jQuery example with an animated sparkline (see Mouse speed example).

https://omnipotent.net/jquery.sparkline/

Is it possible to animate a sparkline in Semiotic via live data or cycling through a fixed range of values? Would be a cool addition.

**Comment by dgwyer** [comment]
Hi Elijah. Was this closed because it's not possible to animate sparklines?

**Comment by emeeks** [comment]
Hey David, no I was just closing a million old issues that never got any attention. You should be able to update data and see it update in a sparkline very easily. Just change the data on a time and you'll see it. I would recommend rendering in canvas, so it doesn't add the overhead of trying to transform the line (which would probably be ugly anyway).

**Comment by dgwyer** [comment]
Thanks Elijah, I'll try it out when I have time.
