### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by fuocor** [nteract/semiotic#316]
I posted back a few months ago [(here)](https://github.com/emeeks/semiotic/issues/137) about typing the library. Unfortunately I was in a little over my head with other work related tasks to take it on,

Well, visualization, has become a priority and I have made some good progress with XYFrame, and created simple wrappers around the others. I will be working with NetworkFrame and OrdinalFrame in the coming weeks. 

I would like to contribute it back to the group, for validation and collaboration....

The approach I took is a little unconventional in that I stubbed the react components into typescript equivalent classes and strong-typed their properties, which I then compile into the type definitions. The advantage is that all the types are validated by the compiler for consistency and should you ever want to migrate the code they'll be there to receive it :).

It makes for come complex generic definitions, but to date, the typing stands up at runtime without using `any` or `object`.

For now it is a stand-alone project, but it can be folded into the code base...

Please let me know if and how you would like to proceed.

rich

**Comment by emeeks** [comment]
In that time I typed much of the library with flow. I don't know how to integrate the two or if the typescript defs live somewhere else but as long as it can be managed I'm all for it.

Why don't you open a PR and we can review it and discuss it there.

**Comment by stereobooster** [comment]
hey @emeeks! As far as I understand since then things changed a bit and part of the library is already converted to TS, right? Is there any roadmap for this process or some tickets to understand where things are? Thanks a lot

**Comment by emeeks** [comment]
Oh this issue is still open. I should close it, as of `1.19.0` Semiotic is entirely in typescript. I still need to clean up the types and export them but that should be separate issues. @stereobooster & @fuocor if either of you are interested in helping with any of that, just let me know.
