### ISSUE TITLE
Keyboard nav with canvas

### ISSUE THREAD

**Issue by mmazanec22** [nteract/semiotic#329]
When I try to use canvasPieces (or canvas etc), the keyboard navigability no longer works.  I realize that this would require changing the way all of the aria stuff works and moving it to the interaction layer :/  Maybe this can just be disclaimed in the docs for now?

**Comment by emeeks** [comment]
I think we should move it to the interaction layer. It should still be working in SVG interactivity, so I'll take a look at that, and also dig into how to enable it in the canvas interaction.
