### ISSUE TITLE
Responsive Axis

### ISSUE THREAD

**Issue by fuocor** [nteract/semiotic#330]
When using the responsive charts I would like to scale the axis accordingly.

With the XYFrame and fixed sizing this is pretty straight forward. Using the responsive sizing it would be nice to get the dimensions as arguments to callbacks for scale and ticks and anything else that is dimension dependent.

below is the example using static sizing.
```
   const scaleExtent = [lines[0].coordinates[0].x, lines[0].coordinates[lines[0].coordinates.length - 1].x];
   {
       scale: d3.scaleLinear().domain(scaleExtent).range([0, size[0]]),
      … rest 
    }
```

thanks,
rich

**Comment by emeeks** [comment]
That's a good idea. Let me take a look into the code and see where I could expose that and how.
