### ISSUE TITLE
ResponsiveMinimapXYFrame with docked Minimap

### ISSUE THREAD

**Issue by fuocor** [nteract/semiotic#331]
I would like the Minimap portion of the ResponsiveMinimapXYFrame to be a fixed height and stretch along the x-Axis, while the XYFrame is responsive to both x & y (minus the height of the MiniMap). 

I'm not sure how to get this done...

Any help is appreciated

rich

**Comment by emeeks** [comment]
MinimapXYFrame abstracts settings to generate a Minimap and accompanying XYFrame. You could create a pair of ResponsiveXYFrames with different settings that had this behavior. I'll try to put together a demo and also see if there's a way to abstract that into a more convenient MinimapXYFrame.

**Comment by fuocor** [comment]
That is what I did :)

thanks
