### ISSUE TITLE
Tooltip position near edge of vis

### ISSUE THREAD

**Issue by mmazanec22** [nteract/semiotic#341]
When a tooltip is going to run off the edge of a visualization, it would be nice if it was repositioned to not do that.

**Comment by mmazanec22** [comment]
I can totally accept "this is a case-by-case business requirements question" or "semiotic's philosophy is to not micromanage/solve every issue" and implement something myself in my project.  But it does seem like a common need that could benefit from a reasonable default (like not running off the screen) with options (like being contained to the vis container dimensions instead).  IDK where exactly the boundary is between library and dev on something like this.

**Comment by niwsa** [comment]
@emeeks Is this achieved by using https://semiotic.nteract.io/guides/annotations#custom-annotation-rules and using adjustedPosition, adjustedSize... ?
