### ISSUE TITLE
Allow <Axis label={string | object} /> to also accept function to dynamically generate axis label

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#347]
Currently `<Axis label={string | object} />` accepts a string or object. I'd like to propose that the name property of the object also allow a function to be defined that has access to the data and frame props.

This would allow you to specify dynamic labels for the axes rather than hard coding them. For example here in your example of a Semiotic scatter chart:

https://codepen.io/dgwyer/pen/BGyMoP

The labels are hard coded as strings `'x'` and `'y'`. I'd like to be able to base these directly off the data or `x` and `y` data accessors.

Going one step further would it be possible to also assign `xAccessor` and `yAccessor` dynamically from the data, and hence automatically assign the axis labels?

So, in an ideal scenario if the `x` and `y` object property names, for each point the `points` array, were changed then the data accessors and axis labels would automatically update.

**Comment by emeeks** [comment]
Could you go into a bit more detail about how this would work and what would be passed to a dynamic axis labeling function to allow you to create meaningful dynamic labels. It's pretty easy to do, I'm just not sure of what approach to take.

The second, dynamic accessors from data, seems very separate and I'm also not sure how that would work. I'd love to hear more about that in a separate issue.

**Comment by dgwyer** [comment]
For my use case it would be valuable to have access to the data (and props) so that I can pull the axis label directly from the data without having to set it manually.

So when the chart data changes the axis labels update automatically. Nice. This makes an assumption of course that the format of the data will be the same but is something that can be handled inside the function.

If you also had access to props then you'd have another option to pull the axis label directly from converting `xAccessor` and `yAccessor` to strings.

I know it's not that much 'work' to manually set axis labels I just like the idea of another level of automation where possible.

I see that the axis label currently accepts a string or an object. Would it make sense to allow the `name` property of the object to accept a string or function, so that you still had access to set the other object properties if required?

Or, would it be best to allow both `label="Units Sold"` and `label={{name: "Units Sold"}}` to also accept functions?

**Comment by dgwyer** [comment]
Hi Elijah. Do you not plan to add this now?

**Comment by emeeks** [comment]
I'll reopen this so we can discuss. I cleared a lot of very old issues because they'd sat moldering for a while. In this case, I'm not sure that it makes sense for a dynamic function, given that any dynamism is handled in changes to other frame props, and so you should be able to make any changes when you change those other props. The purpose of dynamic accessors and such is that you need to apply it differently to different datapoints. If you want to change the axis label when the user changes the data, you could just change the label when the data changes, I don't see this needing further automation. That said, I'm reopening it, could you offer up a use case where the dynamic nature of the data requires a dynamic axis label?

**Comment by dgwyer** [comment]
Thanks for the clarification Elijah it makes a lot of sense. I think I was confusing myself, to be honest.

You're right of course, because the data accessors and axis labels are just props these can be updated via lifecycle methods or hooks easily.

I haven't had a chance to look at Semiotic for a while now but will be using it again on a project soon. I'm looking forward to using v2. Thanks for all your continued hard work on this!
