### ISSUE TITLE
Unsafe lifecycle methods warning

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#363]
I'm getting the following warning in the Chrome console:

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: Mark, VisualizationLayer, XYFrame

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: InteractionLayer, Mark, VisualizationLayer, XYFrame
```

Going forward it's probably a good idea to update the code to remove instances of `componentWillMount` and `componentWillReceiveProps` as these are officially deprecated as legacy methods.

https://reactjs.org/docs/react-component.html#updating

Here's the locations of all instances in Semiotic:
https://github.com/emeeks/semiotic/search?q=componentWillMount&type=Code
https://github.com/emeeks/semiotic/search?q=componentWillReceiveProps&unscoped_q=componentWillReceiveProps

There are also instances found in Semiotic Mark:
https://github.com/emeeks/semiotic-mark/search?q=componentWillMount&unscoped_q=componentWillMount
https://github.com/emeeks/semiotic-mark/search?utf8=%E2%9C%93&q=componentWillReceiveProps&type=

**Comment by emeeks** [comment]
I don't plan on replacing the soonToBeDeprecated lifecycle stuff until a major version change, which I expect to happen with React 17. I'll take a look and see if there's anything I can move into other places that is still compatible with all the React 15 that's out there.

**Comment by dgwyer** [comment]
No problem, just wanted to report what I'm seeing. I'm getting a few console warnings from WordPress React in addition to Semiotic warnings which clogs the console making difficult to debug via the console.

Not a biggie, just a bit distracting.
