### ISSUE TITLE
No documentation for using annotations in OrdinalFrame

### ISSUE THREAD

**Issue by deekshachaudhary** [nteract/semiotic#374]
Still says TODO, please add the documentation as it is very difficult to find out the annotation "type" for Ordinal frame.

**Comment by emeeks** [comment]
I'm sorry about that. I promise new docs will be forthcoming. I will update this issue (and close it) when the new docs drop. Here's the OrdinalFrame annotation types from there:

- **column-hover**: Like frame-hover but the entire column/row is passed to the function.
- **or**: Presents a simple circle annotation with a passed “label” (like “xy” for XYFrame)
- **r**: Creates a threshold annotation at the r value
- **category**: Creates an AnnotationBracket with the passed “title” and/or “label” based on the passed “categories” array (you pass an array of strings that correspond to the oAccessor category names and the bracket is drawn to surround them, which means it will encompass other columns if they are spread apart). Honors the following props:
-     bracketType = "curly" (draw a straight or curly bracket)
-     position = projection === "vertical" ? "top" : "left" (whether to show the bracket on top, left, right or bottom)
-     depth = 30 (how deep the bracket goes into the viz)
-     offset = 0 (how far back from the viz the bracket is)
-     padding = 0 (the amount of pixels added to the edge of the bracket)
- **ordinal-line**: takes an array of “coordinates” and renders a line. Honors the following props:
- points: (bool defaults to false) show points
- interactive: (bool defaults to false) Points have an invisible 15px radius of interactivity as per standard hover annotation settings
- lineStyle: a JSX style object for the line
- pointStyle: a JSX style object or a function that takes a point and returns a JSX style object
- curve: a d3-shape interpolator
- radius: The radius of displayed points

**Comment by bballcode** [comment]
Is there a way to map an annotation to the middle of a stacked bar without manually calculating where that should be?

Basically, apply an annotation to the category but then apply it to the data point that I'm using to style each change in the bar. Or do I have to calculate the rAccessor value?

**Comment by nickcox** [comment]
How does one pass a scaled `r` value when using the `r` type? I seem to get an error unless I supply an `x` property.

```
Unexpected value translate(NaN, 0) parsing transform attribute.
```

But when supplying an `x`

```jsx
annotations={[{ type: 'r', label: Some label', x: 100 }]}
```

the annotation seems to be drawn by pixel offset rather than at the corresponding `r` value.

**Comment by nickcox** [comment]
Hey @emeeks should I open a new issue for this question? Or is there a better place for me to ask it? I did try on stackoverflow but didn't have much luck there either.

**Comment by emeeks** [comment]
Yes please open a new issue.

**Comment by nickcox** [comment]
Actually, on reading the [latest documentation](https://semiotic.nteract.io/api/ordinalframe#annotations--array-) I was able to get this working. For anyone coming after me, here's what I was missing:

> Annotations that have the same data properties that your data has will be automatically placed in the transformed o/r space.

**Comment by bengarvey** [comment]
@nickcox Thanks @nickcox that helped me out a lot. To give an example, I was using an rAccessor in my data and component like this:

```
rAccessor= ['paid_quantity', 'free_quantity']
```

and in the component:
```
rAccessor={rAccessor}
```

So the annotation needs to look like this:
```
const orAnnotations = [ 
  {type: "or", label: "Some text for the label", date: '2016-03-01', paid_quantity: 30} 
]
```
