### ISSUE TITLE
Marginalia annotations don't link properly 

### ISSUE THREAD

**Issue by bballcode** [nteract/semiotic#377]
I'm trying to pass marginalia annotations to a line graph similar to the last example on this page (https://emeeks.github.io/semiotic/#/semiotic/creatinglinechart)

For some reason, they are drawing a point all the way to the left of the screen when I apply them but they are ranking in the correct order/by the right lines. Any idea what I am doing wrong?

It may be an issue with the date axis? I'm passing the annotation value like this:

 annotations={this.state.data.map(movie => ({
                    date: (this.state.maxDate),
                    //line: movie.title,
                    label: movie.title,
                    title: movie.title,
                    type: "react-annotation",
                    color: movie.color
                }))}
lineIDAccessor={"title"}
 annotationSettings={{
                    layout: {
                        type: "marginalia",
                        orient: "right",
                        //characterWidth: 30,
                        //lineWidth: 20,
                        //padding: 2
                    }
                }}

![image](https://user-images.githubusercontent.com/7720071/52310834-c767f400-2972-11e9-94d0-0777975d6a76.png)

**Comment by emeeks** [comment]
I can't reproduce it. You might have some kind of issue with how you're calculating the maxDate. Could you put together a minimal example on Codepen or elsewhere?
