### ISSUE TITLE
Unit Testing for Semiotic components

### ISSUE THREAD

**Issue by stormpython** [nteract/semiotic#401]
Semiotic components need unit tests.

- [ ] annotationLayerBehavior
- [ ] annotationRules
- [ ] canvas
- [ ] data
- [ ] processing
- [ ] storyboard
- [ ] svg
- [ ] untyped_utilities
- [ ] vendor
- [ ] visualizationLayerBehavior
- [ ] Annotation
- [ ] AnnotationLayer
- [ ] Axis
- [ ] Brush
- [ ] DividedLine
- [ ] DownloadButton
- [ ] FacetController
- [ ] Frame
- [ ] InteractionLayer
- [ ] Legend
- [ ] MiniMap
- [ ] MinimapNetworkFrame
- [ ] MinimapXYFrame
- [ ] NetworkFrame
- [ ] OrdinalFrame
- [ ] ResponsiveFrame
- [ ] ResponsiveMinimapXYFrame
- [ ] ResponsiveNetworkFrame
- [ ] ResponsiveOrdinalFrame
- [ ] ResponsiveXYFrame
- [ ] SmartFrame
- [ ] SparkNetworkFrame
- [ ] SparkOrdinalFrame
- [ ] SparkXYFrame
- [ ] VisualizationLayer
- [ ] XYFrame
- [ ] downloadDataMapping
- [ ] index.js

**Comment by willingc** [comment]
This was tracked here: https://github.com/nteract/semiotic/projects/1

These tests are marked as completed in the project. Closing this tracking issue.
