### ISSUE TITLE
Create stacked bar chart without changing the data?

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#452]
In the Semiotic docs for bar charts the data for a standard chart is:

    data: [
      { user: "Jason", tweets: 10, retweets: 5, favorites: 15 },
      { user: "Susie", tweets: 5, retweets: 100, favorites: 100 },
      { user: "Matt", tweets: 20, retweets: 25, favorites: 50 },
      { user: "Betty", tweets: 30, retweets: 20, favorites: 10 },
     ]

And for the stacked bar chart the data is:

    data: [
      { user: "Jason", action: "tweets", value: 10 },
      { user: "Susie", action: "tweets", value: 5 },
      { user: "Matt", action: "tweets", value: 20 },
      { user: "Betty", action: "tweets", value: 30 },
      { user: "Jason", action: "retweets", value: 5 },
      { user: "Susie", action: "retweets", value: 100 },
      { user: "Matt", action: "retweets", value: 25 },
      { user: "Betty", action: "retweets", value: 20 },
      { user: "Jason", action: "favorites", value: 15 },
      { user: "Susie", action: "favorites", value: 100 },
      { user: "Matt", action: "favorites", value: 50 },
      { user: "Betty", action: "favorites", value: 10 }
    ]

This is basically exactly the same data but in a different format.

I'm currently developing a WordPress charts plugin for the new block based editor and am currently experimenting with how to implement various types of charts, starting with the basic standard ones. e.g. the bar chart in this case.

![wp-semiotic](https://user-images.githubusercontent.com/1482075/55563603-29807380-56ee-11e9-89af-b4477e630a93.gif)

When I click the randomize data button new (random) data values are calculated and used to update the chart to simulate the data changing over time.

The problem I have is that the stacked bar chart uses a different data format and it's rather difficult to duplicate the newly created data and change it to the format expected for a stacked bar chart.

Is there currently an easy way to display a stacked bar chart by using the original data set? Or is this possible by implementing a custom rAccessor function?

Even if this is doable I think there is value in adding a new type of entry for the rAccessor such as an array:

    rAccessor: ["tweets", "retweets", "favorites"]

This would create a stacked chart using the series listed, and in the specified order. This means you'd have an easy way to not only select which series were used but also be able to choose the rendering rendering order too!

This could also be used to create group bar charts. (As long as there's an explicit way to differentiate between stacked or grouped)

I think being able to generate and update data for a bar chart (and perhaps other types of chart) is very beneficial. I hope this idea can be explored further.

Also, just compating the two datasets I personally prefer the more compact array of objects. and it doesn't duplicate any values so is easier to digest the data at a glance.

**Comment by emeeks** [comment]
You could pass an array of accessors for the R value, so for instance `rAccessor={["tweets","retweets","favorites"]}` and then you don't have to inflate the data. Each generated piece is decorated with an `rIndex` which indicates which rAccessor was used to make it, so that would drive your styling decisions. Let me know if that doesn't make sense or doesn't apply.

**Comment by dgwyer** [comment]
That was really helpful, thanks. I can now just specify an array of accessors and in any order and it will render properly and update when the data changes.

However, there's an issue with the styling when the accessor order is changed. Because `rIndex` is a numerical value I mapped this to an array containing accessor names. This only works if the accessor order remains unchanged as the mapping array is (of course) fixed.

You can see this in action here: https://codepen.io/dgwyer/pen/wZvgxO

The first stacked chart colors are correct because the accessors are in the correct order as they match the order in the mapping array. But the other stacked charts are not correctly styled because the mapping is out of sync.

What would help in this case is to expose the accessor name as well as the index. Would it be possible to expose this value in a future version? I think this is the `actualRAccessor` variable:

https://github.com/nteract/semiotic/blob/b19a51600c67fb54d839741d0eecf5fb1eff766f/src/components/svg/frameFunctions.tsx#L261

If this value was exposed then it would be possible to dynamically map to the correct color for each accessor. I don't see how this is easily possible with just `rIndex` unless I'm missing something?

Also, how would you go about rendering a group bar chart? I haven't come across this in the docs which is why I opened another issue about adding a grouped bar chart to the examples for completeness. I think that would be a nice addition.

**Comment by emeeks** [comment]
Grouped bar charts are achieved by changing the `type` of an `OrdinalFrame` to `clusterbar`. Let me mull over the other aspects of this and get back to you.
