### ISSUE TITLE
Is there an example for using Labella with Semiotic?

### ISSUE THREAD

**Issue by deekshachaudhary** [nteract/semiotic#453]
The documentation for annotations say Semiotic has built in support for Labella, but I cannot seem to find a way to use Labella with Semiotic to avoid collision of custom react-annotation labels on a pie chart.

**Comment by emeeks** [comment]
Labella is only used in the `marginalia` mode for `annotationSettings` I don't expose it in any more generic way: https://semiotic.nteract.io/guides/annotations#annotation-settings

There is also a `bump` mode that moves annotations around that might have the effect you want. Could you post a codepen with your example and I can take a look.
