### ISSUE TITLE
Tooltip hover positioning to follow mouse?

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#454]
Are there any plans to implement an alternative positioning to tooltips? i.e. something like this:

https://vega.github.io/vega-lite/examples/circle.html
https://vega.github.io/vega-lite/examples/bar.html

Sometimes it's really nice to have the tooltip move out of the way as you're moving the mouse to be able to see what's underneath.

Perhaps a prop could be exposed to specify 'voronoi' or 'mouse' as the tooltip positioning types. A dx and dy offset would also be useful for mouse positioning so you could manually adjust the tooltip position relative to the mouse cursor (in case this needs tweaking for different cursors).

**Comment by emeeks** [comment]
I'll take a look to see if there's a simple way to implement this but I've always found it to be a poor choice design-wise. That said, if there is a simple way to allow it to follow the mouse, I'll implement it.

**Comment by dgwyer** [comment]
Related to this is transitioning between positions for the tooltip. i.e. to have the option for tooltip positions to transition rather than snap. I think this would be a nice addition.

**Comment by emeeks** [comment]
I'm going to close this, I made a design decision when I started this library that I didn't want the tooltip to follow the mouse, I actually think it's a bad design.
