### ISSUE TITLE
Crisp grid and axis lines

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#455]
I noticed this a while back but don't think I opened an issue about it.

It looks like the grid lines and axis lines are being antialiased causing 1px lines to be at least 2px. This makes the lines look ever so slightly fuzzy: https://semiotic.nteract.io/guides/scatterplot

Also, the axis lines are showing as 2px wide, which standout more clearly than the other lines.

![semiotic-antialis-lines](https://user-images.githubusercontent.com/1482075/55644637-6c197d00-57ce-11e9-8772-2bc7ca53acb2.png)

For comparison this chart grid and axis lines look much cripser: https://vega.github.io/vega-lite/examples/circle.html

In Semiotic is the antialiasing being set or is this a side effect of something else perhaps? I think it would make sense to have cripser lines enabled by default if it is being set manually.

**Comment by dgwyer** [comment]
Also, can we control the rendering order of points so they don't render behind axis lines?

**Comment by emeeks** [comment]
You can use CSS to set the style of your axis lines to be `image-rendering: crisp-edges;`. The lines being drawn over the circles are actually axis baselines, which were designed to be drawn over the viz rather than under so if you want you can turn them off by setting `baseline: false` on your axis. I think I can add a `baseline: "under"` as an option, too.

**Comment by dgwyer** [comment]
Did you mean `shape-rendering`? I added the following CSS and this did the trick:

    .visualization-layer .axis-baseline, .background-graphics .tick-line path {
      shape-rendering: crispEdges;
    }

Using contrasting colors the differece is quite clear. I have a pen here you can turn `crispEdges` on/off in the CSS: https://codepen.io/dgwyer/pen/rbLVrM

Do you think it it's worth adding the above styles into the Semiotics docs examples CSS to make rendering grid/axis lines crisper?

https://github.com/nteract/semiotic-docs/blob/f840697b809cef1d31d5485e8903ac0229ed7980/public/semiotic.css

If so I can create a pull request.

Also, re the axis baseline, adding the "under" option would be a good idea so we could keep the baseline visible but render it under the viz if we wanted too.

**Comment by emeeks** [comment]
Yes I think these would be useful to let people know, perhaps in the new Axis docs?
