### ISSUE TITLE
Add function support for title property in XYFrame and OrdinalFrame

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#456]
For tooltips we can pass in the data to customize output:

    tooltipContent: d => (
      <div className="tooltip-content">
        <h4>{d.summary[0].column}:</h4>
        <p>
          {d.summary[0].value} {formatStr(d.summary[0].rName)}
        </p>
      </div>
    ),

This along with the new rName property allows for some nice dynamic customization as the data series doesn't have to be hard coded, as you can see here: https://codepen.io/dgwyer/pen/wZvgxO

I'd like to do something similar for the chart title but we don't have the facility to use a function with the `title` property. If I could use a function then the title could be automated and dynamically reflect the data series name.

**Comment by dgwyer** [comment]
An example of what this might look like is:

        title: d => {
          //
          // access to d.rAccessor here?
          //
          if( typeof(d.rAccessor) === 'string' ) {
            return (
              <text textAnchor="middle">
                <tspan fill={colorHash[rAccessor]}>{capitalizeStr(rAccessor)}</tspan> + {" "}
              </text>
            )
          } else if( typeof(d.rAccessor) === 'array' ) {
            const titleStr = d.rAccessor.map(accessor => `<tspan fill=${colorHash[accessor]}>${capitalizeStr(accessor)}</tspan>`).join(' + ');
            return (
              <text textAnchor="middle">{titleStr}</text>
            )
          } else {
            return (
              <text textAnchor="middle">Bar Chart</text>
            )  
          }
        }

Compare this to the hard coded version:

        title: (
          <text textAnchor="middle">
            <tspan fill={colorHash.tweets}>Tweets</tspan> + {" "}
            <tspan fill={colorHash.retweets}>Retweets</tspan> + {" "}
            <tspan fill={colorHash.favorites}>Fav</tspan>
          </text>
        ),

I know it's a bit more work to setup than just hard coding the title, but now, if the underlying series names change, or the number of series specified changes, or the order of the series is different, we won't have to update the title property manually.

It's independent of the data and acts as the default chart title. I like the idea of automating aspects of charts that have sensible defaults rather than having to setup everything manually.

Perhaps I'm overthinking this? Can it be simplified? Or is it even necessary? If it's not a lot of work adding access to the data for the title then I think it's probably worth it.

**Comment by emeeks** [comment]
I'm going to close this. I think dynamic titling is already well-supported in that you know already what you're passing to rAccessor or whatever and if you're going to change that, you can easily change what you pass to `title`.
