### ISSUE TITLE
Add projection class name for ordinal chart

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#457]
For ordinal charts we get the following markup for accessor labels:

    <g class="ordinal-labels" transform="translate(40,40)">
      <g transform="translate(-3,16.875)"><text text-anchor="end">Jason</text></g>
      <g transform="translate(-3,50.625)"><text text-anchor="end">Susie</text></g>
      <g transform="translate(-3,84.375)"><text text-anchor="end">Matt</text></g>
      <g transform="translate(-3,118.125)"><text text-anchor="end">Betty</text></g>
    </g>

It would be useful to have the value set for `projection` to be added to the container. e.g. for `projection='horizontal'` the output would be:

    <g class="ordinal-labels horizontal" transform="translate(40,40)">
      <g transform="translate(-3,16.875)"><text text-anchor="end">Jason</text></g>
      <g transform="translate(-3,50.625)"><text text-anchor="end">Susie</text></g>
      <g transform="translate(-3,84.375)"><text text-anchor="end">Matt</text></g>
      <g transform="translate(-3,118.125)"><text text-anchor="end">Betty</text></g>
    </g>

This would allow for easier styling depending on projection type.

Also, is there a way to change the translation values for the labels. e.g. when `projection='horizontal'` I'd like to be able to nudge the labels away from the bars.

![add-projection-class](https://user-images.githubusercontent.com/1482075/55734051-ce64be80-5a16-11e9-8943-1a9dc958bbdd.png)

**Comment by emeeks** [comment]
The next version will add the `projection` value to the class of the frame so your container `div` of your frame should have a value like ` vertical frame ordinalframe` for its class.

**Comment by dgwyer** [comment]
Thanks for adding this!

Just one thing I noticed though before closing the issue is that there seems to be a leading space generated before the outputted projection class.

![leading-space](https://user-images.githubusercontent.com/1482075/56030541-ff920700-5d14-11e9-9b02-fbccdb68018d.png)

Is this only when the `className` value is empty here:
https://github.com/nteract/semiotic/commit/2b12cb1ecc0831a35541cd3f9f79fdea72f94253

And is this `className` meant only for internal purposes or can we use it to add custom classes to the chart container div? I didn't find anything in the docs that mentions this.

**Comment by emeeks** [comment]
Yes you should be able to pass a `className` to any frame and it will be decorated there. empty spaces don't matter with CSS classes, so it's not a big deal but I'll see if I can clean that up.
