### ISSUE TITLE
Brushing Parallel Coordinates Chart enters infinite loop unless a 0 value exists in range values

### ISSUE THREAD

**Issue by davidnmora** [nteract/semiotic#474]
### To reproduce
1. Open `src/docs/components/BarToParallel.js` on `master`
2. Delete all objects in `funnelData` which have have 0 in their range property. (In this case, the last two objects are the only ones)
3. Navigate using "FORWARD!" to the Brushable Parallel Coordinate Chart. React reaches stack maximum from loop between `render()` and `brushing()`

### What seems to be going wrong
The brush end handler gets extent data scaled incorrectly (not sure exactly what scale it's using because it doesn't quite seem to be scaled to something sensible like canvas position, as far as I can tell...)

```javascript
brushing(e, c) {
    const columnExtent = this.state.columnExtent
    // e is bogus numbers completely outside the extent of the data, or null
    columnExtent[c] = e 
    this.setState(columnExtent)
 }
```

### My best guess 
Seems like the falsey 0 value is playing some (unintended) but important role in ensuring the extent gets properly translated/set?
I will dig into the source code when I have a bit more time...

Thanks!

**Comment by emeeks** [comment]
Should be resolved in 1.19.11
