### ISSUE TITLE
docs: use data or coordinates consistently for XYFrame examples

### ISSUE THREAD

**Issue by micahstubbs** [nteract/semiotic#479]
big fan of Semiotic, have enjoyed seeing it grow and improve. 

have a nit for the docs:

it would be nice if the examples that use XYFrames used either `coordinates` or `data` consistently.  

I wanted to paste the code from this [nice hover annotation example](https://semiotic.nteract.io/guides/tooltips) into the code for my existing XYFrame graphic, but found that the internal data structure of `lines` was different between the examples. 

alternately, if there is a good reason to use different keys for lines across examples, it would help to call out in the docs why the key names change from example to example.

**Comment by micahstubbs** [comment]
here's an example from the `lines` docs that uses `coordinates` https://semiotic.nteract.io/api/xyframe#lines-data-

**Comment by emeeks** [comment]
Thanks for pointing this out, Micah, I'll take a look and see what we can do around consistency. One issue is that XYFrame accepts arrays or objects with props other than `coordinates` (using `lineDataAccessor`) and we want to demonstrate that for users but maybe it should always be the `coordinates` approach as a default when we're showing off other features.
