### ISSUE TITLE
Typo in API Documentation

### ISSUE THREAD

**Issue by moona3k** [nteract/semiotic#485]
Typo fix request. Something super minor and trivial, but thought it'd be of worth to make note.
Please refer to screenshot below:

![Screen Shot 2019-07-09 at 6 04 37 PM](https://user-images.githubusercontent.com/32221114/60932755-4049df80-a274-11e9-82e6-498c10cc2db2.png)

URL: https://semiotic.nteract.io/guides/highlighting

Thanks!

**Comment by emeeks** [comment]
Thanks for catching this!
