### ISSUE TITLE
Waterfall tooltip

### ISSUE THREAD

**Issue by TijanaStojkov** [nteract/semiotic#489]
I have a problem with tooltips in the waterfall chart. The tooltip position does not follow the position of the bar, but is at the position corresponding to the value (height) of that bar. And the 0 value for tooltip is at 20k

![11](https://user-images.githubusercontent.com/49430834/62426759-443d1600-b6e9-11e9-8e0f-9b24746954de.jpg)
![22](https://user-images.githubusercontent.com/49430834/62426760-44d5ac80-b6e9-11e9-8de0-a0dc9a7e0926.jpg)

My code:

import React, { Component } from 'react';

import OrdinalFrame from "semiotic/lib/OrdinalFrame"
const purple = "#9900ff"
const green = "#9fd0cb"
const red = "#E0488B"

function waterfall({ data, rScale, adjustedSize }) {
  const renderedPieces = []
  let currentY = 0
  let currentValue = 0
  const zeroValue = rScale(0)

  const formatLabel = (name, value) => {
    let label = `${(name === "Total" ? Math.abs(value) : value) / 1000}k`

    if (label[0] === "-") {
      label = label[0] + "$" + label.slice(1)
    } else {
      label = "$" + label
    }
    return label
  }

  const fillRule = d =>
    d.column === "Total" ? purple : d.value > 0 ? green : red

  const keys = Object.keys(data)

  keys.forEach(key => {
    //assume only one per column though...
    const thisPiece = data[key].pieceData[0]
    let value = thisPiece.value
    const name = thisPiece.data.name
    if (name === "Total") {
      value = -currentValue
    } else {
      currentValue += value
    }
    const thisColumn = data[name]

    const { x, width } = thisColumn
    const height = rScale(value) - zeroValue
    const margin = frameProps.margin
    let y = adjustedSize[1] - margin.top - height
    if (height < 0) {
      y = adjustedSize[1] - margin.top
    }
    y += margin.top + currentY

    const markObject = {
      o: key,
      piece: thisPiece,
      renderElement: {
        markType: "g",
        children: []
      },
      xy: {
        x: x + width / 2,
        y: y
      }
    }

    renderedPieces.push(markObject)

    markObject.renderElement.children.push(
      <rect
        height={Math.abs(height)}
        x={x}
        y={y}
        width={width}
        style={{ fill: fillRule(thisPiece) }}
      />
    )
    const lineY = name === "Total" || value > 0 ? y : y + Math.abs(height)

    if (name !== "Total") {
      markObject.renderElement.children.push(
        <line
          x1={x + width}
          x2={x + width + frameProps.oPadding}
          y1={lineY}
          y2={lineY}
          style={{ stroke: "gray", strokeDasharray: "5 5" }}
        />
      )
    }
    const textOffset = name === "Total" || value > 0 ? 15 : -5
    markObject.renderElement.children.push(
      <text
        x={x + width / 2}
        y={lineY + textOffset}
        style={{ fontSize: "10px", textAnchor: "middle", fill: "white" }}
      >
        {formatLabel(name, value)}
      </text>
    )

    currentY -= height
  })

  return renderedPieces
}

const frameProps = {   data: [{ name: "Product Revenue", value: 42000 },
    { name: "Services Revenue", value: 21000 },
    { name: "Fixed Costs", value: -17000 },
    { name: "Variable Costs", value: -14000 },
    { name: "Other Costs", value: -10000 },
    { name: "Ransoms", value: 10000 },
    { name: "Cat Rental", value: 10000 },
    { name: "Total" }],
  size: [700,400],
  margin: { left: 60, top: 40, bottom: 100, right: 20 },
  type: waterfall,
  oPadding: 40,
  oAccessor: "name",
  rAccessor: "value",
  rExtent: [0,65000],
  axes: [{ tickFormat: function(e){return"$"+e/1e3+"k"}, orient: "left" }],
  oLabel: d => <text transform="rotate(45)">{d}</text>,
  pieceHoverAnnotation: true

}

export default () => {
  return <OrdinalFrame {...frameProps} />
}

CSS:
.tooltip-content {
  border: 1px solid black;
  background: white;
  padding: 20px;
  position: relative;
 transform: translate(calc(-50% + 7px), calc(50% - 20px));
}

.tooltip-content:before {
  background: inherit;
  content: "";
  padding: 0px;
  transform: rotate(45deg);
  width: 15px;
  height: 15px;
  position: absolute;
  z-index: 99;
  border-right: inherit;
  border-bottom: inherit;
  bottom: -8px;
  left: calc(50% - 15px);
}

**Comment by emeeks** [comment]
Sorry I took so long to look at this issue, I've fallen behind on supporting Semiotic due to other distractions. But I'm back at it now! This one was weird, partly because the custom type isn't a good story and so you've got all this API that's based on understanding Semiotic internals rather than sensible friendly settings. I hope to make it better in Semiotic 2.0 but for now, here's the fix:

Instead of:

```
const thisPiece = data[key].pieceData[0]
let value = thisPiece.value
const name = thisPiece.data.name
```

Use:

```
const thisPiece = data[key].pieceData[0].data
let value = thisPiece.value
const name = thisPiece.name
```

What's happening is that `pieceData[0]` is the decorated piece and what it's decorated with is some drawing instructions that don't actually make sense for this custom chart. Its `data` property, on the other hand, is just the original data passed to it, and so if you use that, then Semiotic doesn't default to the generated drawing instructions. Hope that makes sense. I'm updating the docs for this example so that it has code like this so that future implementations don't cause the same problem. I'll close this comment when I publish the next version of Semiotic and update the docs.

**Comment by TijanaStojkov** [comment]
Thank you :-)
