### ISSUE TITLE
How could you combine an area chart with a line chart ?, or make thresholds

### ISSUE THREAD

**Issue by SebastianGranados** [nteract/semiotic#501]
I need to make thresholds in a line graph as in the example image
![umbral](https://user-images.githubusercontent.com/43859312/65452827-91935500-de07-11e9-801d-6bb876e1d533.png)

**Comment by torioLuz** [comment]
One way is to use [annotation](https://semiotic.nteract.io/guides/annotations) with type = `bounds`.

**Comment by nitinjs** [comment]
can anyone post fiddle for this?

jsfiddle.net

**Comment by emeeks** [comment]
Drawing summary boxes is actually rather easy (and the extent is calculated from the boxes, so you can use them to set extent:

https://codepen.io/emeeks/pen/YzXOWog
