### ISSUE TITLE
Waterfall + bar chart

### ISSUE THREAD

**Issue by TijanaStojkov** [nteract/semiotic#506]
How do I combine the waterfall chart with a bar chart, like in the image I am sending you.
![WB](https://user-images.githubusercontent.com/49430834/67516087-49827f00-f6a0-11e9-9e8a-d1eaa350f24a.png)

**Comment by emeeks** [comment]
You just have to adjust the rules to expect more than one value per column:

https://codepen.io/emeeks/pen/PoojQzX

**Comment by DeveshChauhan** [comment]
Is there a way to make it horizontal waterfall chart?

**Comment by emeeks** [comment]
@DeveshChauhan Sorry, I didn't notice your comment here. You can adjust the settings to make the chart horizontal. If you'd like an example please feel free to open a new issue.
