### ISSUE TITLE
renderMode disabled transition 

### ISSUE THREAD

**Issue by jefffriesen** [nteract/semiotic#508]
If I transition from `projection: 'vertical'` to `projection: 'horizontal'`, the transition between the projections is smooth. If I use `renderMode: 'sketchy'`, that transition animation stops working and it immediately switches between projections.

It is possible to maintain the transition?

Thanks

**Comment by emeeks** [comment]
No unfortunately there is no animated transition available with sketchy marks because it would require some work underneath to render the in-betweens, which would also be very performance intensive.

**Comment by jefffriesen** [comment]
Ok, good to know. Thanks!
