### ISSUE TITLE
networkframe: sketchy nodes seem to render only in radial (v2.beta-22)

### ISSUE THREAD

**Issue by demartsc** [nteract/semiotic#516]
I am running into a situation where if I apply sketchy nodeRenderMode (and import roughjs as renderingEngine) it appears to always render nodes in the radial, tree layout. Here are some pics for tree and network with sketchy and non-sketchy applied to nodes. 

Network:
![image](https://user-images.githubusercontent.com/22157638/77386520-3c99b280-6d48-11ea-9f36-bd9c4f99ee7a.png)
![image](https://user-images.githubusercontent.com/22157638/77386527-41f6fd00-6d48-11ea-925f-e62cd319fa1b.png)

Tree: 
![image](https://user-images.githubusercontent.com/22157638/77386609-6a7ef700-6d48-11ea-9828-872fb39dbfd1.png)
![image](https://user-images.githubusercontent.com/22157638/77386578-5c30db00-6d48-11ea-9219-7e4e3331233d.png)

**Comment by demartsc** [comment]
Also, I am not sure painty is working, I can get normal and sketch nodes to render, but not painty (they just render as "normal").

**Comment by emeeks** [comment]
Sorry, painty was retired in v2. You are welcome to take a look at old `semiotic-mark` versions and  pull out the function and create a sketchyRenderEngine that draws in that way.

The sketchy redrawing should be fixed in `.23`.
