### ISSUE TITLE
Enhancements regards canvas rendering: retina display and progressive rendering

### ISSUE THREAD

**Issue by BigFatDog** [nteract/semiotic#523]
Hi,
I'm evaluating semiotic for large dataset rendering. Currently I'm using  [canvas integration example](https://semiotic.nteract.io/examples/canvas-interaction). I have observed two potential enhancements:
1. Circles are not sharp on Macbook retina display. I checked [Frame.tsx](https://github.com/nteract/semiotic/blob/master/src/components/Frame.tsx) and found retina support is not turned on for canvases

2. Currently all points are displayed at the same time. It takes a while for the chart to show (this is expected because this is large data set). Is it possible to add progressive rendering? [Parallel Coordinates](http://syntagmatic.github.io/parallel-coordinates/) has such a function. Furthermore, the render progress can be interrupted when end user forces to re-render the chart. A reference implementation is here: [RenderQueue](https://github.com/BigFatDog/parcoords-es/blob/master/src/util/renderQueue.js)

If these enhancements can be included in the future plan, I'm willing to help.

Thanks.

**Comment by emeeks** [comment]
I had no idea about the retina support, I'll take a look at that.

Progressive rendering does need to happen, you're absolutely right. I'll see if I can knock that out if I can carve out the time. If you want to put in a PR, I'd be happy to review it.

**Comment by BigFatDog** [comment]
Both are rendered on canvas. 
Left: retina support on
Right(semiotic): retina support off

<img width="1349" alt="compare-raw-with-retina" src="https://user-images.githubusercontent.com/5818886/81227932-33446c80-8fbb-11ea-8aa7-5001b38426d8.png">

**Comment by emeeks** [comment]
Just pushed support for both retina and progressive rendering. Should be in rc4 as soon as I fix a couple other bugs.

**Comment by BigFatDog** [comment]
Thank you!

**Comment by emeeks** [comment]
Take a look at `2.0.0.rc4` which just got published which should have both.
