### ISSUE TITLE
use of filteredRenderNodes appears to mutate the underlying object array

### ISSUE THREAD

**Issue by demartsc** [nteract/semiotic#524]
When trying to use filterRenderedNodes in the Semiotic Hierarchy tableau extension, I noticed that the data appears to get mutated and never returns back to its original state. Here is a screen shot of where I _think_ this may be happening, hope that is helpful...

![image](https://user-images.githubusercontent.com/22157638/81253483-8deec000-8fdd-11ea-9568-05165669267a.png)

From what i can tell once I send a subset of nodes as true if I try to send another set the original object appears to have been mutated and I only get nodes in both of the two selections rendered. Do let me know if you have any questions on this one.

**Comment by emeeks** [comment]
This should be resolved in `2.0.0.rc4` which just got published.
