### ISSUE TITLE
What's the support for Server-side Rendering Applications?

### ISSUE THREAD

**Issue by kjgarza** [nteract/semiotic#525]
I'm interested on using semiotic in a nextJS application in a SSR app. When using other libraries or D3 with SSR app, I have been experienced problems with showing tooltips and other elements. I am wondering how does semiotic deal with this type of issues ?

**Comment by emeeks** [comment]
It's not designed for server-side rendering, since it uses DOM references due to its reliance on d3-select and associated libraries. I'd like to provide SSR functionality but I don't see that coming this year.

**Comment by salsager** [comment]
@kjgarza in `nextjs` you can use it by using dynamic imports and disabling the `SSR` 
something like: 
```
const Chart = dynamic(
    () => import('../../components/chart/chart'),
    { ssr: false }
);
```
and the chart is using `semiotic`

**Comment by willingc** [comment]
Closing this issue since the questions have been answered.
