### ISSUE TITLE
XYFrame download button not shown

### ISSUE THREAD

**Issue by IvanAbadzhiev** [nteract/semiotic#526]
I want to show a download button for xyframe with summaries and the download button is not shown under this chart. I got deeper and find this condition
```
if (download && (points || lines)) {
```

points and lines are **undefined** and on the next line 
```
 var downloadData = download === "points" ? mapParentsToPoints(fullDataset) : points || lines || summaries || areas;
```

We are checking for summaries and areas.

Why you don't make it to work with summaryData same as points and lines
```
if (download && (points || lines || summaries || areas)) {
```

Thanks

**Comment by emeeks** [comment]
Hi Ivan, unfortunately, I got rid of download functionality for v2, since it was really something people should handle outside of the charting library. I'd be happy to review and merge a PR if you want to file one against v1, though.

**Comment by willingc** [comment]
I'm going to go ahead and close this issue as out of scope for this library. Thanks for using semiotic. ☀️
