### ISSUE TITLE
AnnotationCalloutElbow note title doesn't re-render when the value it uses changes

### ISSUE THREAD

**Issue by vizowl** [nteract/semiotic#530]
I am using semiotic 2.0.0-rc.5 and it appears that react-annotation note titles and and labels do not respond to changes once they have first been rendered.

I have setup a minimal version of the issue here https://github.com/vizowl/semiotic-annotations-issue

I also played with things like creating annotation objects (and arrays) and then using the spread operator to pass them to the XYFrame to see if always creating the object helped - but it didn't.

**Comment by emeeks** [comment]
This should be fixed in rc7 please take a look and let me know.

**Comment by vizowl** [comment]
Thanks - it all looks good to me
