### ISSUE TITLE
warning when using webpack

### ISSUE THREAD

**Issue by colombod** [nteract/semiotic#531]
I am building a library that requires the @nteract/dataExplorer and I get a lot of warnings relates to semiotic like this

```bash
    WARNING in ./node_modules/semiotic/lib/annotationLayerBehavior/annotationHandling.js
    Module Warning (from ./node_modules/source-map-loader/index.js):
    (Emitted value instead of an instance of Error) Cannot find source file '../../src/components/annotationLayerBehavior/annotationHandling.ts': Error: Can't resolve '../../src/components/annotationLayerBehavior/annotationHandling.ts' in .\dotnet-interactive-visualization\src\Microsoft.DotNet.Interactive.DataExplorer.js\node_modules\semiotic\lib\annotationLayerBehavior'
     @ ./node_modules/semiotic/lib/AnnotationLayer.js 59:27-82
     @ ./node_modules/semiotic/lib/index.js
     @ ./node_modules/@nteract/data-explorer/lib/components/DataExplorer.js
     @ ./node_modules/@nteract/data-explorer/lib/index.js
     @ ./src/interface.ts
     @ ./src/index.ts
```

The project I am building is [this one](https://github.com/colombod/dotnet-interactive-visualization/tree/master/src/Microsoft.DotNet.Interactive.DataExplorer.js) and it is using this [package.json](https://github.com/colombod/dotnet-interactive-visualization/blob/d1c36123ebc13b1219e9ebeb8c4fed14c0623012/src/Microsoft.DotNet.Interactive.DataExplorer.js/package.json#L1)

**Comment by emeeks** [comment]
I just deprecated that version of data-explorer it shouldn't have been published with that dependency. Sorry for the hassle.

**Comment by colombod** [comment]
8.2.7 gives me same warning

**Comment by emeeks** [comment]
Ah, can you share with me your full error?

**Comment by colombod** [comment]
[error.txt](https://github.com/nteract/semiotic/files/5045164/error.txt)
Attaching the file, seems to be mostly source map resolution problems now

**Comment by colombod** [comment]
I am now facing another issue, when I load the umd output of web pack I can see the components
![image](https://user-images.githubusercontent.com/375556/89893600-8f2d1b80-dbd0-11ea-8cf9-3c7720259668.png)
But do not see any rendering when switching to any rendering other than the table, is there anything I am missing? I don't see any error in the dev tools console or network tab

![image](https://user-images.githubusercontent.com/375556/89893733-cd2a3f80-dbd0-11ea-8b6c-98f19c157ed5.png)

![image](https://user-images.githubusercontent.com/375556/89893755-d9ae9800-dbd0-11ea-800f-8ed148c19cc7.png)

@captainsafia do you have any hint?

**Comment by willingc** [comment]
Just an update, the next version will be modernizing our development tool chain to use Parcel. Closing this issue as this migration has begun.
