### ISSUE TITLE
Line overlaying candlestick 

### ISSUE THREAD

**Issue by justinsoliz** [nteract/semiotic#532]
Is there any guidance for plotting two distinct data sets e.g. a moving avg over a candlestick plot. 

I see an example for a [bar / line combo](https://semiotic.nteract.io/examples/bar-line-chart) but that seems to be slightly different given the two axes.

**Comment by emeeks** [comment]
In XYFrame, you can pass the candlestick data as `points` and pass the moving average data as `lines` would that solve your problem?

**Comment by justinsoliz** [comment]
I will give that a try, thanks!
