### ISSUE TITLE
donut and rose display wrong percentage 

### ISSUE THREAD

**Issue by BigFatDog** [nteract/semiotic#534]
**General**

donut and rose display wrong percentage  while pie is correct, with the same data.

**Re-produce:**
I directly use sample code from donut, pie and rose, and try with the following data:
```
[{x: 0, y: 150}, {x:1, y: 115698}]
```
the corresponding config is:
``
        oAccessor={"x"}
        rAccessor={"y"}
``

**Version**
 `1.20.5` and `2.0.0-rc5`

Please see attached images

**Comment by BigFatDog** [comment]
<img width="381" alt="截屏2020-09-26 上午11 23 43" src="https://user-images.githubusercontent.com/5818886/94344258-09342b00-ffec-11ea-8c21-e69affa6137a.png">
<img width="335" alt="截屏2020-09-26 上午11 25 43" src="https://user-images.githubusercontent.com/5818886/94344259-09342b00-ffec-11ea-9013-399b92ef90b0.png">

**Comment by emeeks** [comment]
Well that's not good. Will take a look at it.

**Comment by emeeks** [comment]
This is fixed in `2.0.0-rc.12`. The problem was that it wasn't handling ordinal values created with numbers (in your case the `x` values).

**Comment by BigFatDog** [comment]
Thank you.
