### ISSUE TITLE
Is there a way to pass a function to legend items and make them interactive?

### ISSUE THREAD

**Issue by bengarvey** [nteract/semiotic#535]
Working on a force directed graph and I'd love to be able to click a legend item and have it toggle that type of edge on or off. Is there way to pass in a function to do that? Ideally something like this:

```
let legendGroups = [ 
  { type: 'line',
    styleFn: d => (
      { stroke: d.color,
        strokeOpacity: 0.5,
        strokeWidth: "3px"
      }), 
    items: [
      { label: "Ancestor", color: colors.ancestor, onClick: {() => this.toggleRelationship('ancestor')} },
      { label: "Trained", color: colors.trained, onClick: {() => this.toggleRelationship('trained')}  },
      { label: "Killed", color: colors.killed, onClick: {() => this.toggleRelationship('killed')}  },
    ]   
  }
]
```

**Comment by hydrosquall** [comment]
From the looks of it such a property doesn't currently exist

https://github.com/nteract/semiotic/blob/d79503d7b90f25b6776c7b3e957ba3a12c87b1c5/src/components/types/legendTypes.tsx#L5-L7

However, I think I have an idea about where to add this. My suggestion would be to make the group itself take the `customClickBehavior` handler (for consistency with other parts of this library, e.g. https://semiotic.nteract.io/api/xyframe#customclickbehavior--function- ), and pass a reference to the clicked item in the callback, e.g. in your example:

```js
let legendGroups = [ 
  { type: 'line',
    styleFn: d => (
      { stroke: d.color,
        strokeOpacity: 0.5,
        strokeWidth: "3px"
      }),
    customClickBehavior: d => { this.toggleRelationship(item.value) } ,
    items: [
      { label: "Ancestor", color: colors.ancestor, value: 'ancestor' } },
      { label: "Trained", color: colors.trained, value: 'trained' }  },
      { label: "Killed", color: colors.killed, value: 'killed' )}  },
    ]   
  }
]
```

 What do you think, @emeeks ?

**Comment by emeeks** [comment]
I would simply pass `d` but otherwise yes I think this is good functionality to add to the legend. It would be nice if it had hover behavior, too but I worry about how that might cause issues with rerendering. Feel free to start a PR and I would be happy to give more feedback.

**Comment by emeeks** [comment]
@bengarvey & @hydrosquall I finally managed to carve out some time, so sorry about how long it took. Take a look at 1.20.6 and see if it works for you.
