### ISSUE TITLE
Hide tooltip on mouse out

### ISSUE THREAD

**Issue by rkz2021** [nteract/semiotic#544]
Trying to make the tooltip content selectable using the solution provided here - https://codepen.io/emeeks/pen/GdOGZZ?editors=0110. Is there a way to hide the tooltip on mouse out of each node?

**Comment by ShahirZain** [comment]
hi I saw your code here may be a solution , you can do like this
![image](https://user-images.githubusercontent.com/30791669/121880879-f69f8480-cd27-11eb-9341-24b27489f8c3.png)

**Comment by rkz2021** [comment]
Tried this as well, not working

**Comment by rkz2021** [comment]
Let me explain the scenario in detail - in the sample given in codepen(https://codepen.io/emeeks/pen/GdOGZZ?editors=0110), the tooltip content gets changed when mouse over moves from one bar to another. But the tooltip is not hiding on mouse out of the bar or container. Once the tooltip is displayed, it's not going off without refreshing the page.
