### ISSUE TITLE
Support React 17 [was: Project maintenance]

### ISSUE THREAD

**Issue by Midnighter** [nteract/semiotic#545]
Hi,

Originally I came to ask for plans to support React 17 but then I saw that there basically hasn't been any activity in the last two years. Are there plans to pick up this project again or maintain it in general? Thank you for any insights.

**Comment by ellenbechtel** [comment]
Hi there, I have the same question! Thanks

**Comment by willingc** [comment]
Hi @Midnighter and @ellenbechtel,

We are currently working on updating the nteract project (beginning with nteract/nteract repo) to React 17. While there hasn't been much PR activity on this repo (as it's a mature project), it is maintained by the nteract volunteers. If you would like to help migrate this repo to React 17, we would welcome a PR. Thanks!

cc/ @emeeks

**Comment by willingc** [comment]
Closed by #568. This will be in the upcoming release of Semiotic v2 (estimated date early 2022). Thanks @alexeyraspopov for the PR to get to React 17.
