### ISSUE TITLE
Use Vercel to deploy developer documentation for latest

### ISSUE THREAD

**Issue by willingc** [nteract/semiotic#566]
- [x] Vercel project added for repo
- [ ] Add a parcel command for docs preview build so Vercel can display link for each PR.
- [ ] Decide if / where to deploy a version of documentation connected to HEAD of main

**Comment by alexeyraspopov** [comment]
@willingc seems like this issue is resolved now?

**Comment by willingc** [comment]
Yep, I got it running reliably yesterday and forgot to close this issue. Thanks for the reminder 👍🏼
