### ISSUE TITLE
Decide whether to consolidate semiotic and semiotic-docs repo

### ISSUE THREAD

**Issue by willingc** [nteract/semiotic#572]
As we move to 2.0 and beyond, let's take a look at modernizing our documentation toolchain and content.

Possible ideas and random thoughts (please share  more in the chat):
- [x] create a monorepo (pros / cons)
- [ ] strive for beautiful colors and typography such as in the existing docs
- [ ] interactivity in examples
- [ ] doc review of existing components

FYI @emeeks @alexeyraspopov David Gwer (asked status on Slack)

**Comment by emeeks** [comment]
@alexeyraspopov & I have been discussing it and we feel like combining the main repo and the docs repo is the way to go. So, unless anyone has a compelling counterargument, that's how we're going to do it.

**Comment by alexeyraspopov** [comment]
There are several benefits from having docs as a part of main repo I see:

1. A single source of truth for both devs and users. This is where can have all Semiotic-related discussions, make atomic updates in both code and docs, align the package and docs release cycle
2. The docs website can start using Semiotic code from main branch so we can find regressions and bugs sooner
3. Single repo means simply fewer things to manage

I was planning to open a PR to pull the docs in this repo, possibly preserving git history.

**Comment by willingc** [comment]
I agree. Let's do it.

**Comment by willingc** [comment]
Decision made to create a monorepo. @alexeyraspopov will get us started on combining the repos.

**Comment by alexeyraspopov** [comment]
@emeeks I tried to figure out which branch of semiotic-docs to pull in, and I'm not sure: `semiotic-2` has changes that are not in main and possibly does not have some changes from main
<img width="499" alt="image" src="https://user-images.githubusercontent.com/858295/146857721-f5a06aae-56f4-4c73-a562-4d549eb06732.png">

Do you remember any specific items from `main` branch that can possibly be cherry-picked to `semiotic-2`?

**Comment by willingc** [comment]
@alexeyraspopov I did an interactive rebase and this branch ([semi-together](https://github.com/nteract/semiotic-docs/tree/semi-together)) should resolve conflicts with main and have the 4 commits ahead from semiotic-2. Building the styleguidist docs works from head of the semi-together branch.

**Comment by alexeyraspopov** [comment]
@willingc, the branch looks good, I'll use it for migration. Thanks!

**Comment by alexeyraspopov** [comment]
The PR is ready: https://github.com/nteract/semiotic/pull/578
