### ISSUE TITLE
Transition tooltip position

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#614]
At the moment the tooltip position 'snaps' between locations when points are hovered over.

![transition-tooltip-position](https://user-images.githubusercontent.com/1482075/150817468-7d647042-c851-471b-babc-866b5dc6f1d5.gif)

I've been trying to get this to transition via CSS without any success. Is there an way we can get this to work?

**Comment by emeeks** [comment]
You should be able to achieve this with some simple CSS:

```
.annotation-xy-label {
  transition-property: top, left;
  transition-duration: 0.25s;
}
```
