### ISSUE TITLE
More position options for the legend

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#618]
At the moment we have two options to position the legend to the `left` or `right` of the chart area. There are plenty of times that I need the legend to be displayed (centered) above or below the chart too, such as when one of the data series labels is too long.

![image 8](https://user-images.githubusercontent.com/1482075/151183613-8f97ff4b-90f9-44f5-9b0c-38eef2922fe5.png)

It would be nice to be able to do something like this (mockup):

![Frame 1](https://user-images.githubusercontent.com/1482075/151185851-ee4abfd0-33a2-4010-bc52-bd5d1ab21e84.png)

While I think of it, adding the legend inside the chart area looks good too (obviously this depends on the number of series and the specific data):

![image 14](https://user-images.githubusercontent.com/1482075/151191265-83dc539a-200b-4c28-8636-3bb512d12963.png)

Also, it would be very useful to have other settings to:
- Control the gap between legend items. This should be applied vertically for the default legend, and horizontally when the legend orientation is set to horizontal.
- Disable the legend title and the line drawn underneath (don't need it when displaying the legend above or below the chart).
- Add a margin around the legend.
- Wrap legend series nicely when displaying horizontally. If you have more than, say, 3 or 4 series then this may be needed.

**Comment by emeeks** [comment]
This definitely needs to happen. I think we can offer the interior options as well, though I doubt we can do anything smart (like avoiding regions with datapoints) for a while, despite the fact that we have the capability to do it.

**Comment by dgwyer** [comment]
Manual placement of the legend inside the chart would be fine for now I think. And dynamic positioning could be looked into in the future perhaps?

**Comment by emeeks** [comment]
I've evolved my thinking on legends. I think any kind of more exhaustive legend should be built 3rd party rather than built into Semiotic because of the different kinds of legends and the functionality they include (interactivity for instance).
