### ISSUE TITLE
Traditional Implementation of Parallel Coordinates

### ISSUE THREAD

**Issue by mohithingorani** [nteract/semiotic#63]
Hello @emeeks. Are there any examples of the traditional parallel coordinates currently available (with different values on each axis) with semiotic?
It would be great if you could point me in the right direction.

Thanks!
Mohit

**Comment by wbuchanan** [comment]
@mohithingorani 
Are you sure you would want the variables to all retain their original values as opposed to standardizing the values or using some other method to place all the data on the same scale?  A Sankey diagram can serve the same purpose as parallel coordinates without exposing all of the individual datum in the visualization.

**Comment by mohithingorani** [comment]
@wbuchanan thanks for the input! unfortunately, each axis is unique and interactions (filtering) is important for the visualization.

**Comment by wbuchanan** [comment]
@mohithingorani
Out of curiosity, how do you help your end users with interpreting the visualization if they don’t have much visualization and/or stats background?  If the interpretation of the slopes vary from one set of points to another I would imagine you would get lots of confusion when people are attempting to interpret things overall and the slopes don’t have a constant interpretation from one set of points to the next.

**Comment by mohithingorani** [comment]
@wbuchanan Parallel Coordinates isn't just a data viz, it serves as an excellent interface for further data exploration. One can quickly derive subsections of data using the range sliders, which are extremely intuitive. The slope of lines depends a lot on the ordering of attributes, which I intend to pay close attention to. Since it is an internal tool, I can train my stakeholders to use it correctly.
Hope that helps!

**Comment by emeeks** [comment]
It's an interesting challenge and one that I haven't taken up because by design Semiotic doesn't allow for different scales. But I know how I'd implement it and I'll go ahead and do so to see what you think. I'll try to put it together tomorrow.

**Comment by emeeks** [comment]
You can see parallel coordinates here at the penultimate step:
https://semiotic.nteract.io/examples/bar-to-parallel-coordinates
